

typeset -U path cdpath fpath manpath

for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/kxhl949fqrr9zkncf5hq2m94gi74dck8-zsh-5.9/share/zsh/$ZSH_VERSION/help"





# Oh-My-Zsh/Prezto calls compinit during initialization,
# calling it twice causes slight start up slowdown
# as all $fpath entries will be traversed again.


source /nix/store/anrjb298x3pj4ffra35vywl3v23z80c0-zsh-autosuggestions-0.7.0/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git)

ZSH_THEME="intheloop"
source $ZSH/oh-my-zsh.sh






# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY


# Costom command
neofetch
eval "$(direnv hook zsh)"


# Aliases
alias cd2='cd ../..'
alias cdawesome='cd nixos/hosts/awesome/'
alias cddwm='cd nixos/hosts/dwm/'
alias cdhome='cd nixos/modules/home-manager/'
alias cdhypr='cd nixos/hosts/hyprland/'
alias gc='git clone'
alias rebawesome='sudo nixos-rebuild switch --flake ~/nixos/#awesome'
alias rebdwm='sudo nixos-rebuild switch --flake ~/nixos/#dwm'
alias rebhypr='sudo nixos-rebuild switch --flake ~/nixos/#hyprland'
alias updatenix='sudo nix flake update'
alias vi='nvim'
alias vihome='vi home.nix'
alias vim='nvim'
alias vinix='vi configuration.nix'

# Named Directory Hashes


source /nix/store/zdb7qbp09si3wq3hxbldf4ap7knhpyim-zsh-syntax-highlighting-0.7.1/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS+=()



